import Head from "next/head";
import Link from "next/link";
import { ReactElement } from "react";
import ThirdPartyEmailPassword from "supertokens-auth-react/recipe/thirdpartyemailpassword";
import Layout from "../layouts";
import DashboardLayout from "../layouts/dashboard";
import type { NextPageWithLayout } from "./_app";

const Dashboard: NextPageWithLayout = () => {
  return (
    <ThirdPartyEmailPassword.ThirdPartyEmailPasswordAuth>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Bliszter</h1>
        <Link href="/">
          <a>Back Home</a>
        </Link>
      </main>
    </ThirdPartyEmailPassword.ThirdPartyEmailPasswordAuth>
  );
};

Dashboard.getLayout = function getLayout(page: ReactElement) {
  return (
    <Layout>
      <DashboardLayout>{page}</DashboardLayout>
    </Layout>
  );
};
export default Dashboard;
