import type { NextPage } from "next";
import React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Logout from "../components/logout";
import styles from "../styles/Home.module.css";
import DeleteUser from "../components/deleteUser";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Bliszter</h1>
        <Link href="/editor">
          <a>Markdown Editor</a>
        </Link>
        <Link href="/protectedPage">
          <a>Protected Pege</a>
        </Link>
        <Logout />
        <DeleteUser />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
